package bookplugin

import (
	"archive/zip"
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/Cylunex/shadow-relay/internal/security"
)

//go:embed runner.py
var runner string

// Files generates executable code only from Relay's embedded, reviewed template.
// Metadata is JSON (a YAML subset); values never interpolate into Python source.
func Files(e Entry, updated string) (map[string][]byte, error) {
	if !identifier.MatchString(e.ID) || !strings.HasPrefix(e.ID, "relay_") || e.Recipe == nil || len(e.Blockers) > 0 {
		return nil, errors.New("only supported entries can become plugins")
	}
	r := *e.Recipe
	if err := Validate(&r); err != nil {
		return nil, err
	}
	date, err := time.Parse(time.RFC3339Nano, updated)
	if err != nil {
		return nil, errors.New("invalid plugin timestamp")
	}
	marshal := func(v any) []byte { b, _ := json.MarshalIndent(v, "", "  "); return append(b, '\n') }

	metadata := map[string]any{"contractVersion": "1.0", "id": e.ID, "name": r.Name, "author": "Shadow Relay", "version": Version(r), "type": "source", "domains": r.Domains, "baseUrls": []string{r.BaseURL}, "capabilities": []string{"search", "detail", "toc", "chapter"}, "enabled": true, "language": r.Language, "auth": map[string]any{"mode": "none"}, "content": map[string]any{"access": "unknown", "paid": "unknown"}, "tags": []string{"thirdparty", "relay-generated"}, "rateLimit": map[string]any{"perHostConcurrency": 1, "minIntervalMs": r.MinIntervalMS}, "proxy": map[string]any{"mode": "never", "required": false}, "browser": map[string]string{"mode": "none"}, "sourceSeed": map[string]string{"type": e.Upstream, "upstreamId": e.SourceID}, "accessStrategy": map[string]string{"search": "http", "detail": "http", "toc": "http", "chapter": "http"}}
	if r.Language == "" {
		metadata["language"] = "zh-CN"
	}
	smoke := map[string]any{"keyword": r.SmokeKeyword, "fixtures": map[string]any{}, "expect": map[string]any{"search": map[string]int{"minResults": 1}, "toc": map[string]any{"complete": false, "minChapters": 1, "requireUniqueChapterUrls": true, "requireSequentialIndexes": true}, "chapter": map[string]int{"minContentLength": 200}}, "relayDraft": true}
	fixtures := smoke["fixtures"].(map[string]any)
	for _, name := range []string{"search", "detail", "toc", "chapter"} {
		fixtures[name] = map[string]string{"url": r.BaseURL, "file": name + ".html"}
	}
	files := map[string][]byte{"source.py": []byte(runner), "metadata.yaml": marshal(metadata), "recipe.json": marshal(map[string]any{"id": e.ID, "updated": date.UTC().Format("2006-01-02"), "recipe": r}), "smoke/smoke.yaml": marshal(smoke), "README.md": []byte(fmt.Sprintf("# %s\n\nGenerated by Shadow Relay from %s. No imported scripts are executed.\n\nCompatibility is structural, not live verification. The smoke fixtures are explicitly drafts; use integrations/hub/capture_smoke.py in the Hub environment to capture authorized live responses and exact TOC expectations. Do not claim directory completeness before that check.\n\nWarnings: %v\n", r.Name, e.Upstream, e.Warnings))}
	for _, name := range []string{"search", "detail", "toc", "chapter"} {
		files["smoke/fixtures/"+name+".html"] = []byte("<!-- Relay draft: capture a real authorized response before fixture verification. -->\n")
	}
	return files, nil
}

func Archive(report Report, updated string) ([]byte, error) {
	if len(report.Entries) > 500 {
		return nil, errors.New("split plugin packages into at most 500 entries")
	}
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	index, _ := json.MarshalIndent(report, "", "  ")
	f, e := w.Create("compatibility.json")
	if e != nil {
		return nil, e
	}
	if _, e = f.Write(index); e != nil {
		return nil, e
	}
	for _, entry := range report.Entries {
		if entry.Recipe == nil || len(entry.Blockers) > 0 {
			continue
		}
		files, e := Files(entry, updated)
		if e != nil {
			return nil, e
		}
		names := []string{}
		for name := range files {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			f, e := w.Create("plugins/sources/thirdparty/" + entry.ID + "/" + name)
			if e != nil {
				return nil, e
			}
			if _, e = f.Write(files[name]); e != nil {
				return nil, e
			}
		}
	}
	if e := w.Close(); e != nil {
		return nil, e
	}
	return buf.Bytes(), nil
}

func Version(r Recipe) string {
	b, _ := json.MarshalIndent(r, "", "  ")
	b = append(b, '\n')
	return "0.2.0+" + security.Hash(append(b, []byte(runner)...))[:12]
}
